### ISSUE TITLE
Add uglifyJS back into the project

### ISSUE THREAD

**Issue by vperron** [Polyconseil/systematic#13]
Source maps do not seem to work very well on `make dist`. We tried:
- This issue only happens when the flag `--optimize-minimize` is given.
- Use `webpack.optimize.UglifyJsPlugin` instead of `--optimize-minimize`
- There is a warning in bluetils-js with ui-router source map missing, but is does not seem to be the root of the problem.

**Comment by vperron** [comment]
Seems to work now. Still, some apps fail when ran, especially because ng-annotate seems not to have been applied.

**Comment by vperron** [comment]
It doesn't work. Need further analysis.

**Comment by raphael-boucher** [comment]
With angular, I checked that `make dist` without optimization outputs an annotated bundle, as expected.

**Comment by stephane** [comment]
Build still not minified, any news on that?
