### ISSUE TITLE
Weird Makefile in 0.7.0 package

### ISSUE THREAD

**Issue by rbarrois** [Polyconseil/systematic#38]
It seems the packager forgot to cleanup their workdir: the installed packages contains an interesting Makefile ;)

``` make
# cat node_modules/systematic/Makefile



define readme
$(shell sed -nr '/\[$(2)\]/,/\[/{/$(3)/p}' $(1) | sed -ne 's/^\s*$(3)\s*=\s*//p')
endef



rahan := $(call readme,systematic.ini,build,xprofile)
rahan := $(if $(rahan),$(rahan),chouchou)

truc:
    @echo $(rahan)
```

**Comment by vperron** [comment]
Most definitely a test Makefile that got embedded somehow. We should have a look at the `.npmignore` / package.json's `files` section to prevent this, probably.

Why not leveraging `git ls-files` upon releasing as well. We'll look into that !
